---
services:
  db:
   image: suchitmolugu/lib-py-project:dbimage
   ports:
     - "3306:3306"
   deploy:
     replicas: 2
   volumes:
     - db_data:/var/lib/mysql

  auth_service:
    image: suchitmolugu/lib-py-project:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 2

  book_service:
    image:  suchitmolugu/lib-py-project:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 2

  borrow_service:
    image:  suchitmolugu/lib-py-project:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 2

  frontend:
    image:  suchitmolugu/lib-py-project:frontendimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
volumes:
  db_data:
    
